name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'hotfix'
  - title: '🧰 Maintenance'
    label: 'chore'
exclude-labels:
  - 'skip-changelog'
replacers:
  - search: '/FN-(\d{1,4})/g'
    replace: '[FN-$1](https://betconstruct.atlassian.net/browse/FN-$1)'
autolabeler:
  - label: 'bug'
    branch:
      - '/bugfix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'release'
    branch:
      - '/release\/.+/'
  - label: 'skip-changelog'
    branch:
      - '/release\/.+/'
  - label: 'skip-changelog'
    branch:
      - '/develop\/.+/'
template: |
  ## Changes

  $CHANGES
change-template: '* $TITLE'
