name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'hotfix'
  - title: '🧰 Maintenance'
    label: 'chore'
exclude-labels:
  - 'skip-changelog'
replacers:
  - search: '/\[FN-(\d{4})\]/g'
    replace: 'https://betconstruct.atlassian.net/browse/FN-$1'
autolabeler:
  - label: 'bug'
    branch:
      - '/bugfix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES